{{- if and .Values.ingress.enabled .Values.ingress.web.enabled .Values.ingress.web.hostname }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kodus.fullname" . }}-web
  labels:
    {{- include "kodus.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.web.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.web.hostname | quote }}
      secretName: {{ default (printf "%s-web-tls" (include "kodus.fullname" .)) .Values.ingress.web.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.web.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kodus.fullname" . }}-web
                port:
                  number: {{ .Values.web.port }}
{{- end }}
