{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kodus.fullname" . }}-webhooks
  labels:
    {{- include "kodus.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhooks
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webhooks.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kodus.componentSelectorLabels" (dict "root" . "component" "webhooks") | nindent 4 }}
{{- end }}
