{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kodus.fullname" . }}-api
  labels:
    {{- include "kodus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kodus.componentSelectorLabels" (dict "root" . "component" "api") | nindent 4 }}
{{- end }}
