apiVersion: v1
entries:
  kodus:
  - apiVersion: v2
    appVersion: 2.1.24
    created: "2026-07-09T17:45:26.928024809Z"
    description: Helm chart for self-hosted Kodus AI (stateless components only)
    digest: 71ecf6db8b1f1cc16b32e86c644ccc4699db44e9cbfc012f562bfdce83f40c70
    home: https://kodus.io
    keywords:
    - kodus
    - ai
    - code-review
    kubeVersion: '>=1.28.0-0'
    maintainers:
    - name: Community contributors
      url: https://github.com/mzglinski/kodus-helm-chart
    name: kodus
    sources:
    - https://github.com/kodustech/kodus-ai
    - https://github.com/mzglinski/kodus-helm-chart
    type: application
    urls:
    - https://mzglinski.github.io/kodus-helm-chart/charts/kodus-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-09T17:45:26.926067055Z"
