name: Release Please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      release-as:
        description: "Release as"
        required: false
        default: ""

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v5
        with:
          config-file: release-please-config.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-as: ${{ inputs.release-as }}
